development:
  application_host: <%= ENV.fetch('APPLICATION_HOST') { 'localhost' } %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV.fetch('MAILER_FROM_EMAIL') { 'noreply@bebraven.org' } %>
  mailer_deliveray_override_address: <%= ENV['MAILER_DELIVERY_OVERRIDE_ADDRESS'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  # This value comes from here: https://canvas.instructure.com/doc/api/file.lti_dev_key_config.html#launch-overview
  lti_oidc_base_uri: <%= ENV.fetch('LTI_OIDC_BASE_URI') { 'https://canvas.instructure.com' } %>
  csp_frame_ancestors_host: <%= ENV.fetch('CSP_FRAME_ANCESTORS_HOST') { nil } %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { 'localhost' } %>
  smtp_server: <%= ENV.fetch('SMTP_SERVER') { 'localhost' } %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 587 } %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>

test:
  application_host: <%= ENV.fetch('APPLICATION_HOST') { 'localhost' } %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  mailer_deliveray_override_address: <%= ENV['MAILER_DELIVERY_OVERRIDE_ADDRESS'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  lti_oidc_base_uri: <%= ENV.fetch('LTI_OIDC_BASE_URI') { 'https://example.lms.com' } %>
  csp_frame_ancestors_host: <%= ENV.fetch('CSP_FRAME_ANCESTORS_HOST') { nil } %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { 'localhost' } %>
  smtp_server: <%= ENV.fetch('SMTP_SERVER') { 'localhost' } %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 587 } %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>

staging:
  application_host: <%= ENV.fetch('APPLICATION_HOST') { nil } %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  mailer_deliveray_override_address: <%= ENV['MAILER_DELIVERY_OVERRIDE_ADDRESS'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  lti_oidc_base_uri: <%= ENV.fetch('LTI_OIDC_BASE_URI') { 'https://canvas.instructure.com' } %>
  csp_frame_ancestors_host: <%= ENV.fetch('CSP_FRAME_ANCESTORS_HOST') { nil } %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { 'localhost' } %>
  smtp_server: <%= ENV.fetch('SMTP_SERVER') { 'localhost' } %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 587 } %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>

production:
  application_host: <%= ENV.fetch('APPLICATION_HOST') { nil } %>
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  mailer_deliveray_override_address: <%= ENV['MAILER_DELIVERY_OVERRIDE_ADDRESS'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_write_key: <%= ENV['HONEYCOMB_WRITE_KEY'] %>
  lti_oidc_base_uri: <%= ENV.fetch('LTI_OIDC_BASE_URI') { 'https://canvas.instructure.com' } %>
  csp_frame_ancestors_host: <%= ENV.fetch('CSP_FRAME_ANCESTORS_HOST') { nil } %>
  salesforce_consumer_key: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_KEY'] %>
  salesforce_consumer_secret: <%= ENV['SALESFORCE_PLATFORM_CONSUMER_SECRET'] %>
  salesforce_username: <%= ENV['SALESFORCE_PLATFORM_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PLATFORM_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_PLATFORM_SECURITY_TOKEN'] %>
  smtp_domain: <%= ENV.fetch('SMTP_DOMAIN') { 'localhost' } %>
  smtp_server: <%= ENV.fetch('SMTP_SERVER') { 'localhost' } %>
  smtp_port: <%= ENV.fetch('SMTP_PORT') { 587 } %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>

